calibration_offset:
- 0.0035926674
- 1.7880281
- -1.5459236
- -0.60479313
- 0.00076940347
- 0.0
joint_limits:
  elbow_flex:
  - 0
  - 180
  gripper:
  - 0
  - 100
  shoulder_lift:
  - -90
  - 90
  shoulder_pan:
  - -180
  - 180
  wrist_flex:
  - -90
  - 90
  wrist_roll:
  - -180
  - 180
motion:
  interpolation_steps: 50
  max_acceleration: 2.0
  max_velocity: 1.0
  timestep: 0.02
port: /dev/ttyACM0
use_degrees: true
